### ISSUE TITLE
Unable to change the default status_code list in statuscake

### ISSUE THREAD

**Issue by danhul** [labynocle/ansible-statuscake#14]
I have one uptime test to a URL that by default returns "403". For the uptime test not to report down time when it gets "403" I set a variable "status_codes_csv: " with a comma separated list of HTTP status codes without "403" in the list. But when the test is created in Statuscake, it contains the default HTTP status codes. The module doesn't seem to update the list based on the input I set.

**Comment by labynocle** [comment]
oh !
Thank you for the report @danhul 

Just to be sure how you call the plugin, can you share me your task (without the creds of course) ?

I try to take a look as soon as possible !

**Comment by danhul** [comment]
Hi @labynocle, thank you ver much for your fast response. 
I was looking at only the module and you point me to the right direction :)
I checked the task and the reference to status codes was "item.status_codes" while in ansible test specification I set the variable "status_code_csv". Now I changed the task to use either the default list or the "item.status_codes_csv" and now it works.  👍

**Comment by labynocle** [comment]
perfect then! :smile: 

thank you for using this little script !
